# Generated by Django 5.2.17 on 2026-09-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_canonicalise_phone_numbers'),
        ('core', '0011_organizationsettings_sms_credit_balance_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='delegation',
            constraint=models.CheckConstraint(condition=models.Q(('role__isnull', False), models.Q(('codenames', []), _negated=True), _connector='OR'), name='delegation_delegates_something'),
        ),
    ]
