# Generated by Django 5.2.17 on 2026-09-18 21:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_delegation_delegation_delegates_something'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='day_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Default cost of a day for this role, excluding VAT. Not pay.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='user',
            name='day_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Cost of a day of this person's time, excluding VAT. Not pay.", max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
