# Generated by Django 5.2.17 on 2026-08-21 19:57

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0002_enable_rls'),
        ('core', '0008_alter_auditlog_actor'),
        ('locations', '0003_enable_rls'),
        ('network', '0002_enable_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drum_number', models.CharField(db_index=True, max_length=100)),
                ('initial_length', models.DecimalField(decimal_places=3, max_digits=14)),
                ('remaining_length', models.DecimalField(decimal_places=3, max_digits=14)),
                ('uom', models.CharField(default='m', max_length=20)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('USED_SERVICEABLE', 'Used — serviceable'), ('FAULTY', 'Faulty'), ('DAMAGED', 'Damaged'), ('SCRAP', 'Scrap')], max_length=20)),
                ('owner_type', models.CharField(choices=[('OWN', 'Own stock'), ('CLIENT', 'Client-owned (consignment)')], max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed — nothing left')], default='OPEN', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('current_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reels', to='locations.stocknode')),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reels', to='catalogue.itemtype')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
                ('owner_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reels', to='network.client')),
            ],
            options={
                'ordering': ('drum_number',),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SerialUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serial_number', models.CharField(db_index=True, max_length=150)),
                ('asset_tag', models.CharField(blank=True, db_index=True, max_length=100)),
                ('source', models.CharField(choices=[('MANUFACTURER', 'Manufacturer serial'), ('INTERNAL', 'Internally generated asset tag')], default='MANUFACTURER', max_length=20)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('USED_SERVICEABLE', 'Used — serviceable'), ('FAULTY', 'Faulty'), ('DAMAGED', 'Damaged'), ('SCRAP', 'Scrap')], max_length=20)),
                ('owner_type', models.CharField(choices=[('OWN', 'Own stock'), ('CLIENT', 'Client-owned (consignment)')], max_length=10)),
                ('status', models.CharField(choices=[('IN_STOCK', 'In stock'), ('IN_CUSTODY', 'Held by a person'), ('INSTALLED', 'Installed at a site'), ('QUARANTINED', 'Quarantined'), ('RETURNED_TO_CLIENT', 'Returned to the client'), ('SCRAPPED', 'Scrapped')], default='IN_STOCK', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('current_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serial_units', to='locations.stocknode')),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serial_units', to='catalogue.itemtype')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
                ('origin_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recovered_units', to='network.site')),
                ('owner_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='serial_units', to='network.client')),
            ],
            options={
                'ordering': ('serial_number',),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('USED_SERVICEABLE', 'Used — serviceable'), ('FAULTY', 'Faulty'), ('DAMAGED', 'Damaged'), ('SCRAP', 'Scrap')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('uom', models.CharField(blank=True, max_length=20)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='catalogue.itemtype')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='locations.stocknode')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
                ('owner_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='network.client')),
            ],
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('movement_type', models.CharField(choices=[('RECEIPT', 'Received'), ('ISSUE', 'Issued'), ('TRANSFER', 'Transferred'), ('INSTALL', 'Installed at a site'), ('CONSUME', 'Consumed on site'), ('RETURN', 'Returned'), ('QUARANTINE', 'Moved to quarantine'), ('RESTORE', 'Restored to serviceable'), ('DISPOSE', 'Disposed of'), ('ADJUST', 'Adjusted after a count'), ('REVERSAL', 'Reversal of an earlier movement')], max_length=20)),
                ('tracking_mode', models.CharField(choices=[('SERIALIZED', 'Serialized — each unit individually identified'), ('BULK', 'Bulk — a counted quantity'), ('REEL', 'Reel — a measured length on a numbered drum')], max_length=20)),
                ('uom', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('owner_type', models.CharField(choices=[('OWN', 'Own stock'), ('CLIENT', 'Client-owned (consignment)')], max_length=10)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('USED_SERVICEABLE', 'Used — serviceable'), ('FAULTY', 'Faulty'), ('DAMAGED', 'Damaged'), ('SCRAP', 'Scrap')], max_length=20)),
                ('document_type', models.CharField(blank=True, db_index=True, max_length=50)),
                ('document_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('document_line_id', models.CharField(blank=True, max_length=64)),
                ('document_number', models.CharField(blank=True, help_text='The document number as issued, for reporting.', max_length=50)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements_out', to='locations.stocknode')),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='catalogue.itemtype')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
                ('owner_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='network.client')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='stock.reel')),
                ('reversal_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='stock.stockmovement')),
                ('serial_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='stock.serialunit')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements_in', to='locations.stocknode')),
            ],
            options={
                'ordering': ('-occurred_at', '-id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='reel',
            index=models.Index(fields=['organization', 'status'], name='stock_reel_organiz_70de28_idx'),
        ),
        migrations.AddConstraint(
            model_name='reel',
            constraint=models.UniqueConstraint(fields=('organization', 'drum_number'), name='uniq_drum_number_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='reel',
            constraint=models.CheckConstraint(condition=models.Q(('initial_length__gt', 0)), name='reel_starts_with_a_length'),
        ),
        migrations.AddConstraint(
            model_name='reel',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_length__gte', 0)), name='reel_remainder_is_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='reel',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_length__lte', models.F('initial_length'))), name='reel_remainder_does_not_exceed_its_start'),
        ),
        migrations.AddIndex(
            model_name='serialunit',
            index=models.Index(fields=['organization', 'current_node'], name='stock_seria_organiz_7b4cd3_idx'),
        ),
        migrations.AddConstraint(
            model_name='serialunit',
            constraint=models.UniqueConstraint(fields=('organization', 'serial_number'), name='uniq_serial_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='serialunit',
            constraint=models.UniqueConstraint(condition=models.Q(('asset_tag__gt', '')), fields=('organization', 'asset_tag'), name='uniq_asset_tag_per_organization'),
        ),
        migrations.AddIndex(
            model_name='stockbalance',
            index=models.Index(fields=['organization', 'item_type'], name='stock_stock_organiz_e34590_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbalance',
            index=models.Index(fields=['organization', 'node'], name='stock_stock_organiz_058d38_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbalance',
            index=models.Index(fields=['organization', 'owner_client'], name='stock_stock_organiz_96c2fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.UniqueConstraint(fields=('organization', 'node', 'item_type', 'owner_client', 'condition'), name='uniq_balance_per_node_item_owner_condition', nulls_distinct=False),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['organization', 'occurred_at'], name='stock_stock_organiz_d19d14_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['organization', 'item_type', 'occurred_at'], name='stock_stock_organiz_cc28de_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['organization', 'serial_unit', 'occurred_at'], name='stock_stock_organiz_630833_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['organization', 'reel', 'occurred_at'], name='stock_stock_organiz_d169cb_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['organization', 'document_type', 'document_id'], name='stock_stock_organiz_dc51de_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['organization', 'to_node', 'item_type'], name='stock_stock_organiz_666cf7_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['organization', 'from_node', 'item_type'], name='stock_stock_organiz_80b8be_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='movement_quantity_is_positive'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('from_node', models.F('to_node')), _negated=True), name='movement_moves_somewhere'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner_client__isnull', False), ('owner_type', 'CLIENT')), models.Q(('owner_client__isnull', True), ('owner_type', 'OWN')), _connector='OR'), name='client_owned_movement_names_its_client'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tracking_mode', 'SERIALIZED'), _negated=True), models.Q(('quantity', 1), ('serial_unit__isnull', False)), _connector='OR'), name='serialized_movement_is_one_identified_unit'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tracking_mode', 'REEL'), _negated=True), ('reel__isnull', False), _connector='OR'), name='reel_movement_names_its_drum'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tracking_mode', 'BULK'), _negated=True), models.Q(('reel__isnull', True), ('serial_unit__isnull', True)), _connector='OR'), name='bulk_movement_has_no_serial_or_drum'),
        ),
    ]
