# Generated by Django 5.2.17 on 2026-08-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_count_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='from_condition',
            field=models.CharField(blank=True, choices=[('NEW', 'New'), ('USED_SERVICEABLE', 'Used — serviceable'), ('FAULTY', 'Faulty'), ('DAMAGED', 'Damaged'), ('SCRAP', 'Scrap')], help_text='Condition it was held in, when the movement changed it.', max_length=20),
        ),
    ]
