# Generated by Django 5.2.17 on 2026-09-18 20:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_enable_rls'),
        ('core', '0011_organizationsettings_sms_credit_balance_and_more'),
        ('locations', '0003_enable_rls'),
        ('network', '0009_subcontractor_rls'),
        ('stock', '0005_stockmovement_from_condition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Value per unit as at this movement, excluding VAT (D24).', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='unit_cost_source',
            field=models.CharField(choices=[('CATALOGUE', "The item type's unit cost"), ('CLIENT_DECLARED', 'Declared by the client on issue'), ('NONE', 'Unvalued')], default='NONE', help_text='Where the valuation came from, so an unvalued movement is visibly unvalued rather than silently zero.', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('unit_cost__isnull', True), ('unit_cost_source', 'NONE')), models.Q(('unit_cost__isnull', False), models.Q(('unit_cost_source', 'NONE'), _negated=True)), _connector='OR'), name='a_valued_movement_says_where_the_value_came_from'),
        ),
    ]
