# Generated by Django 5.2.17 on 2026-10-03 04:53

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.manager
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_enable_rls'),
        ('core', '0014_boxes'),
        ('locations', '0003_enable_rls'),
        ('network', '0009_subcontractor_rls'),
        ('receiving', '0005_gate_in_line_declared_value'),
        ('stock', '0006_movement_valuation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=100)),
                ('source', models.CharField(choices=[('LABEL', 'From a label'), ('INTERNAL', 'Generated here')], max_length=10)),
                ('depth', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('label_text', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('current_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boxes', to='locations.stocknode')),
                ('gate_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boxes', to='receiving.gatein')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='stock.box')),
            ],
            options={
                'ordering': ('code',),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='serialunit',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='units', to='stock.box'),
        ),
        migrations.CreateModel(
            name='BoxBulkContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('USED_SERVICEABLE', 'Used — serviceable'), ('FAULTY', 'Faulty'), ('DAMAGED', 'Damaged'), ('SCRAP', 'Scrap')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulk_contents', to='stock.box')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='box_contents', to='catalogue.itemtype')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
                ('owner_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='box_contents', to='network.client')),
            ],
            options={
                'ordering': ('id',),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='BoxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Box created'), ('UNIT_IN', 'Unit put in'), ('UNIT_OUT', 'Unit taken out'), ('BULK_IN', 'Bulk put in'), ('BULK_OUT', 'Bulk taken out'), ('BOX_IN', 'Box put in'), ('BOX_OUT', 'Box taken out'), ('MOVED', 'Box moved'), ('CLOSED', 'Box closed')], max_length=20)),
                ('condition', models.CharField(blank=True, choices=[('NEW', 'New'), ('USED_SERVICEABLE', 'Used — serviceable'), ('FAULTY', 'Faulty'), ('DAMAGED', 'Damaged'), ('SCRAP', 'Scrap')], max_length=20)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('document_type', models.CharField(blank=True, max_length=50)),
                ('document_id', models.CharField(blank=True, max_length=64)),
                ('document_number', models.CharField(blank=True, max_length=50)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='stock.box')),
                ('child_box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='stock.box')),
                ('item_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogue.itemtype')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
                ('owner_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='network.client')),
                ('serial_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='box_events', to='stock.serialunit')),
            ],
            options={
                'ordering': ('-occurred_at', '-id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='box',
            index=models.Index(fields=['organization', 'current_node', 'status'], name='stock_box_organiz_24258f_idx'),
        ),
        migrations.AddConstraint(
            model_name='box',
            constraint=models.UniqueConstraint(models.F('organization'), django.db.models.functions.text.Lower('code'), name='uniq_box_code_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='box',
            constraint=models.CheckConstraint(condition=models.Q(('depth__gte', 1), ('depth__lte', 3)), name='box_depth_is_one_to_three'),
        ),
        migrations.AddConstraint(
            model_name='box',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'CLOSED'), _negated=True), ('closed_at__isnull', False), _connector='OR'), name='a_closed_box_says_when'),
        ),
        migrations.AddIndex(
            model_name='boxbulkcontent',
            index=models.Index(fields=['organization', 'item_type'], name='stock_boxbu_organiz_a0059f_idx'),
        ),
        migrations.AddConstraint(
            model_name='boxbulkcontent',
            constraint=models.UniqueConstraint(fields=('box', 'item_type', 'owner_client', 'condition'), name='uniq_box_content_per_item_owner_condition', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='boxbulkcontent',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='box_content_quantity_is_positive'),
        ),
        migrations.AddIndex(
            model_name='boxevent',
            index=models.Index(fields=['organization', 'box', 'occurred_at'], name='stock_boxev_organiz_1cdf02_idx'),
        ),
        migrations.AddIndex(
            model_name='boxevent',
            index=models.Index(fields=['organization', 'serial_unit', 'occurred_at'], name='stock_boxev_organiz_bbb9ae_idx'),
        ),
    ]
