# Generated by Django 5.2.17 on 2026-10-03 12:50

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_enable_rls'),
        ('core', '0015_release_scan_required'),
        ('locations', '0003_enable_rls'),
        ('network', '0009_subcontractor_rls'),
        ('stock', '0008_box_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='earmark_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='earmarked_reels', to='network.site'),
        ),
        migrations.AddField(
            model_name='serialunit',
            name='earmark_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='earmarked_serial_units', to='network.site'),
        ),
        migrations.CreateModel(
            name='BulkEarmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('USED_SERVICEABLE', 'Used — serviceable'), ('FAULTY', 'Faulty'), ('DAMAGED', 'Damaged'), ('SCRAP', 'Scrap')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulk_earmarks', to='catalogue.itemtype')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulk_earmarks', to='locations.stocknode')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
                ('owner_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bulk_earmarks', to='network.client')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulk_earmarks', to='network.site')),
            ],
            options={
                'ordering': ('id',),
                'indexes': [models.Index(fields=['organization', 'node', 'item_type'], name='stock_bulke_organiz_cf1018_idx')],
                'constraints': [models.UniqueConstraint(fields=('site', 'node', 'item_type', 'owner_client', 'condition'), name='uniq_bulk_earmark_per_site_lot', nulls_distinct=False), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='bulk_earmark_quantity_is_positive')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='EarmarkEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('EARMARKED', 'Earmarked'), ('CHANGED', 'Earmark changed'), ('CLEARED', 'Earmark cleared'), ('DELIVERED', 'Delivered to its site'), ('DIVERTED', 'Diverted to another site'), ('MOVED', 'Moved inside the yard'), ('REDUCED', 'Reduced by a correction')], max_length=20)),
                ('condition', models.CharField(blank=True, choices=[('NEW', 'New'), ('USED_SERVICEABLE', 'Used — serviceable'), ('FAULTY', 'Faulty'), ('DAMAGED', 'Damaged'), ('SCRAP', 'Scrap')], max_length=20)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('document_type', models.CharField(blank=True, max_length=50)),
                ('document_id', models.CharField(blank=True, max_length=64)),
                ('document_number', models.CharField(blank=True, max_length=50)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogue.itemtype')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='locations.stocknode')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
                ('owner_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='network.client')),
                ('reel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='earmark_events', to='stock.reel')),
                ('serial_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='earmark_events', to='stock.serialunit')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='network.site')),
                ('to_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='network.site')),
            ],
            options={
                'ordering': ('-occurred_at', '-id'),
                'indexes': [models.Index(fields=['organization', 'site', 'occurred_at'], name='stock_earma_organiz_2bf8ae_idx'), models.Index(fields=['organization', 'to_site', 'occurred_at'], name='stock_earma_organiz_06dc51_idx'), models.Index(fields=['organization', 'action', 'occurred_at'], name='stock_earma_organiz_6d3582_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
