# Generated by Django 5.2.17 on 2026-10-09 15:56

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0017_finance_settings_attachment_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('VEHICLE', 'Vehicle'), ('GENERATOR', 'Generator'), ('TOOL', 'Tool'), ('EQUIPMENT', 'Equipment'), ('OTHER', 'Other')], max_length=12)),
                ('name', models.CharField(max_length=200)),
                ('tag', models.CharField(blank=True, max_length=40)),
                ('tag_key', models.CharField(blank=True, editable=False, max_length=40)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('purchase_terms', models.TextField(blank=True)),
                ('make', models.CharField(blank=True, max_length=80)),
                ('model', models.CharField(blank=True, max_length=80)),
                ('insurance_expires_on', models.DateField(blank=True, null=True)),
                ('inspection_expires_on', models.DateField(blank=True, null=True)),
                ('insurance_alerted_for', models.DateField(blank=True, null=True)),
                ('inspection_alerted_for', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=8)),
                ('closed_on', models.DateField(blank=True, null=True)),
                ('closed_reason', models.CharField(blank=True, choices=[('SOLD', 'Sold'), ('WRITTEN_OFF', 'Written off')], max_length=12)),
                ('closed_note', models.TextField(blank=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='held_assets', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
            ],
            options={
                'ordering': ('name',),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AssetHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handed_over_on', models.DateField()),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handovers', to='assets.asset')),
                ('from_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('handed_over_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
                ('to_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-handed_over_on', '-id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(condition=models.Q(('tag_key', ''), _negated=True), fields=('organization', 'tag_key'), name='uniq_asset_tag_per_org'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'CLOSED'), _negated=True), models.Q(('closed_on__isnull', False), models.Q(('closed_reason', ''), _negated=True)), _connector='OR'), name='a_closed_asset_records_when_and_why'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(('type', 'VEHICLE'), models.Q(('make', ''), ('model', ''), ('insurance_expires_on__isnull', True), ('inspection_expires_on__isnull', True)), _connector='OR'), name='a_vehicle_only_fields_need_a_vehicle'),
        ),
        migrations.AddConstraint(
            model_name='assethandover',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('from_holder__isnull', True), ('to_holder__isnull', True), _negated=True), models.Q(('from_holder', models.F('to_holder')), _negated=True)), name='a_handover_changes_hands'),
        ),
    ]
