# Generated by Django 5.2.17 on 2026-10-09 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_enable_rls'),
        ('network', '0015_projectsite_organization_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='network.supplier'),
        ),
    ]
