# Generated by Django 5.2.17 on 2026-08-21 20:41

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0002_enable_rls'),
        ('core', '0008_alter_auditlog_actor'),
        ('locations', '0003_enable_rls'),
        ('network', '0002_enable_rls'),
        ('stock', '0004_count_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GateOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Awaiting approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PARTIALLY_RELEASED', 'Partially released'), ('RELEASED', 'Released'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], db_index=True, default='DRAFT', editable=False, max_length=20)),
                ('purpose_type', models.CharField(choices=[('INSTALLATION', 'Installation'), ('MAINTENANCE', 'Maintenance'), ('RETURN_TO_CLIENT', 'Return to client'), ('TRANSFER', 'Transfer to another location'), ('DISPOSAL', 'Disposal'), ('TOOL_ISSUE', 'Tool issue')], max_length=30)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('vehicle_reg', models.CharField(blank=True, max_length=30)),
                ('driver_name', models.CharField(blank=True, max_length=200)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('client_uuid', models.UUIDField(blank=True, null=True)),
                ('reject_reason', models.CharField(blank=True, max_length=500)),
                ('cancel_reason', models.CharField(blank=True, max_length=500)),
                ('close_reason', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gate_outs', to='network.client')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('custody_holder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gate_outs_held', to=settings.AUTH_USER_MODEL)),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gate_outs', to='locations.location')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gate_outs_requested', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gate_outs', to='network.site')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='dispatch.gateout')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inbound_gate_outs', to='locations.location')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gate_outs', to='network.workorder')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GateOutLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracking_mode', models.CharField(choices=[('SERIALIZED', 'Serialized — each unit individually identified'), ('BULK', 'Bulk — a counted quantity'), ('REEL', 'Reel — a measured length on a numbered drum')], max_length=20)),
                ('requested_qty', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('released_qty', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('uom', models.CharField(max_length=20)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('USED_SERVICEABLE', 'Used — serviceable'), ('FAULTY', 'Faulty'), ('DAMAGED', 'Damaged'), ('SCRAP', 'Scrap')], default='NEW', max_length=20)),
                ('owner_type', models.CharField(choices=[('OWN', 'Own stock'), ('CLIENT', 'Client-owned (consignment)')], default='OWN', max_length=10)),
                ('is_returnable', models.BooleanField(default=False)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('line_number', models.PositiveIntegerField(default=1)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('gate_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='dispatch.gateout')),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gate_out_lines', to='catalogue.itemtype')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
                ('owner_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gate_out_lines', to='network.client')),
            ],
            options={
                'ordering': ('line_number', 'id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GateOutLineReel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length_requested', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('length_released', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reels', to='dispatch.gateoutline')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gate_out_lines', to='stock.reel')),
            ],
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GateOutLineSerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('released', models.BooleanField(default=False)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serials', to='dispatch.gateoutline')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
                ('serial_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gate_out_lines', to='stock.serialunit')),
            ],
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseVariance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_qty', models.DecimalField(decimal_places=3, max_digits=14)),
                ('released_qty', models.DecimalField(decimal_places=3, max_digits=14)),
                ('reason', models.CharField(max_length=500)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('gate_out_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variances', to='dispatch.gateoutline')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='gateout',
            index=models.Index(fields=['organization', 'status', '-created_at'], name='dispatch_ga_organiz_b65a76_idx'),
        ),
        migrations.AddIndex(
            model_name='gateout',
            index=models.Index(fields=['organization', 'custody_holder'], name='dispatch_ga_organiz_530c9a_idx'),
        ),
        migrations.AddIndex(
            model_name='gateout',
            index=models.Index(fields=['organization', 'expires_at'], name='dispatch_ga_organiz_3b3e4a_idx'),
        ),
        migrations.AddConstraint(
            model_name='gateout',
            constraint=models.UniqueConstraint(condition=models.Q(('number__gt', '')), fields=('organization', 'number'), name='uniq_gate_out_number_per_org'),
        ),
        migrations.AddConstraint(
            model_name='gateout',
            constraint=models.UniqueConstraint(condition=models.Q(('client_uuid__isnull', False)), fields=('organization', 'client_uuid'), name='uniq_gate_out_client_uuid_per_org'),
        ),
        migrations.AddConstraint(
            model_name='gateout',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('client__isnull', True), ('site__isnull', False), ('to_location__isnull', True), ('work_order__isnull', True)), models.Q(('client__isnull', True), ('site__isnull', True), ('to_location__isnull', True), ('work_order__isnull', False)), models.Q(('client__isnull', False), ('site__isnull', True), ('to_location__isnull', True), ('work_order__isnull', True)), models.Q(('client__isnull', True), ('site__isnull', True), ('to_location__isnull', False), ('work_order__isnull', True)), _connector='OR'), name='gate_out_has_exactly_one_destination'),
        ),
        migrations.AddConstraint(
            model_name='gateoutline',
            constraint=models.CheckConstraint(condition=models.Q(('released_qty__gte', 0)), name='released_qty_is_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='gateoutline',
            constraint=models.CheckConstraint(condition=models.Q(('released_qty__lte', models.F('requested_qty'))), name='released_qty_does_not_exceed_what_was_approved'),
        ),
        migrations.AddConstraint(
            model_name='gateoutline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner_client__isnull', False), ('owner_type', 'CLIENT')), models.Q(('owner_client__isnull', True), ('owner_type', 'OWN')), _connector='OR'), name='client_owned_gate_out_line_names_its_client'),
        ),
        migrations.AddConstraint(
            model_name='gateoutlinereel',
            constraint=models.UniqueConstraint(fields=('line', 'reel'), name='uniq_reel_per_gate_out_line'),
        ),
        migrations.AddConstraint(
            model_name='gateoutlinereel',
            constraint=models.CheckConstraint(condition=models.Q(('length_released__lte', models.F('length_requested'))), name='reel_length_released_does_not_exceed_request'),
        ),
        migrations.AddConstraint(
            model_name='gateoutlineserial',
            constraint=models.UniqueConstraint(fields=('line', 'serial_unit'), name='uniq_serial_per_gate_out_line'),
        ),
        migrations.AddIndex(
            model_name='releasevariance',
            index=models.Index(fields=['organization', 'acknowledged_at'], name='dispatch_re_organiz_951cf1_idx'),
        ),
    ]
