# Generated by Django 5.2.17 on 2026-08-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_enable_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateoutline',
            name='no_serial_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
