# Generated by Django 5.2.17 on 2026-09-18 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0004_gate_out_work_order_becomes_project'),
        ('jobs', '0005_job_delivery_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateout',
            name='job',
            field=models.ForeignKey(blank=True, help_text='The job this material is for. Optional; it is what makes a pass project material (O5).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gate_outs', to='jobs.job'),
        ),
    ]
