# Generated by Django 5.2.17 on 2026-10-03 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0005_gate_out_job_attribution'),
        ('stock', '0008_box_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateoutline',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gate_out_lines', to='stock.box'),
        ),
    ]
