# Generated by Django 5.2.17 on 2026-10-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0006_gate_out_line_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateoutline',
            name='divert_reason',
            field=models.TextField(blank=True),
        ),
    ]
