# Generated by Django 5.2.17 on 2026-08-21 20:41

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_webauthncredential'),
        ('catalogue', '0002_enable_rls'),
        ('core', '0008_alter_auditlog_actor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(db_index=True, max_length=50)),
                ('document_id', models.CharField(db_index=True, max_length=64)),
                ('document_number', models.CharField(blank=True, max_length=50)),
                ('level', models.PositiveIntegerField(default=1, help_text='Higher levels are more senior. Levels approve in order.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ESCALATED', 'Escalated'), ('SUPERSEDED', 'Superseded')], db_index=True, default='PENDING', max_length=20)),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('escalated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('required_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to='accounts.role')),
            ],
            options={
                'ordering': ('level', 'id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('AUTO', 'Automatically approved — no approval required')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('auth_method', models.CharField(choices=[('PASSWORD', 'Password'), ('WEBAUTHN', 'Fingerprint or platform authenticator'), ('SYSTEM', 'Automatic, no human actor')], default='PASSWORD', max_length=20)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('decided_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('delegation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_actions', to='accounts.delegation')),
                ('on_behalf_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
                ('webauthn_credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_actions', to='accounts.webauthncredential')),
                ('approval_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='approvals.approvalrequest')),
            ],
            options={
                'ordering': ('-decided_at',),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criticality', models.CharField(choices=[('NONE', 'None'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_rules', to='catalogue.itemcategory')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
                ('required_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_rules', to='accounts.role')),
            ],
            options={
                'ordering': ('-sequence', 'criticality'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['organization', 'document_type', 'document_id'], name='approvals_a_organiz_19239d_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['organization', 'status', 'due_at'], name='approvals_a_organiz_36db86_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalaction',
            index=models.Index(fields=['organization', '-decided_at'], name='approvals_a_organiz_7ac829_idx'),
        ),
        migrations.AddConstraint(
            model_name='approvalaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decision', 'REJECTED'), _negated=True), models.Q(('reason', ''), _negated=True), _connector='OR'), name='rejection_records_a_reason'),
        ),
        migrations.AddConstraint(
            model_name='approvalaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', True), ('decision', 'AUTO')), models.Q(models.Q(('decision', 'AUTO'), _negated=True), ('actor__isnull', False)), _connector='OR'), name='human_decisions_name_their_actor'),
        ),
        migrations.AddConstraint(
            model_name='approvalrule',
            constraint=models.UniqueConstraint(fields=('organization', 'category', 'criticality', 'required_role'), name='uniq_approval_rule_per_scope', nulls_distinct=False),
        ),
    ]
