# Generated by Django 5.2.17 on 2026-08-21 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_webauthn_rls'),
        ('approvals', '0002_enable_rls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequest',
            name='required_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to='accounts.role'),
        ),
    ]
