# Generated by Django 5.2.17 on 2026-09-18 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_delegation_delegation_delegates_something'),
        ('approvals', '0003_alter_approvalrequest_required_role'),
        ('core', '0011_organizationsettings_sms_credit_balance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='required_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests_addressed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['organization', 'required_user', 'status'], name='approvals_a_organiz_6501d8_idx'),
        ),
        migrations.AddConstraint(
            model_name='approvalrequest',
            constraint=models.CheckConstraint(condition=models.Q(('required_role__isnull', True), ('required_user__isnull', True), _connector='OR'), name='a_request_is_addressed_to_a_role_or_a_person_not_both'),
        ),
    ]
