# Generated by Django 5.2.17 on 2026-09-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0004_request_required_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalaction',
            name='self_approved',
            field=models.BooleanField(default=False),
        ),
    ]
