# Generated by Django 5.2.17 on 2026-10-09 07:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_backfill_seeded_role_permissions'),
        ('approvals', '0005_action_self_approved'),
        ('core', '0016_serial_corrected_audit_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='approvalrequest',
            name='a_request_is_addressed_to_a_role_or_a_person_not_both',
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='required_permission',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddConstraint(
            model_name='approvalrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('required_role__isnull', True), ('required_user__isnull', True)), models.Q(('required_permission', ''), ('required_role__isnull', True)), models.Q(('required_permission', ''), ('required_user__isnull', True)), _connector='OR'), name='a_request_has_at_most_one_addressee'),
        ),
    ]
