# Generated by Django 5.2.17 on 2026-08-21 20:10

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0002_enable_rls'),
        ('core', '0008_alter_auditlog_actor'),
        ('locations', '0003_enable_rls'),
        ('network', '0002_enable_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GateIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('VOID', 'Void')], db_index=True, default='DRAFT', max_length=20)),
                ('source_type', models.CharField(choices=[('PURCHASE', 'Purchase — own stock'), ('CLIENT_ISSUE', 'Client issue — consignment stock'), ('RECOVERY', 'Recovery from a decommissioned or demolished site'), ('RETURN_FROM_SITE', 'Unused material returning from site'), ('WARRANTY_RETURN', 'Warranty or faulty return'), ('TRANSFER', 'Transfer from another location')], max_length=30)),
                ('supplier_name', models.CharField(blank=True, max_length=200)),
                ('received_at', models.DateTimeField()),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('client_delivery_note_ref', models.CharField(blank=True, max_length=100)),
                ('client_uuid', models.UUIDField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=500)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gate_ins', to='network.client')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
                ('origin_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recoveries', to='network.site')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gate_ins', to='locations.location')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-received_at', '-id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GateInLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracking_mode', models.CharField(choices=[('SERIALIZED', 'Serialized — each unit individually identified'), ('BULK', 'Bulk — a counted quantity'), ('REEL', 'Reel — a measured length on a numbered drum')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('uom', models.CharField(max_length=20)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('USED_SERVICEABLE', 'Used — serviceable'), ('FAULTY', 'Faulty'), ('DAMAGED', 'Damaged'), ('SCRAP', 'Scrap')], default='NEW', max_length=20)),
                ('owner_type', models.CharField(choices=[('OWN', 'Own stock'), ('CLIENT', 'Client-owned (consignment)')], default='OWN', max_length=10)),
                ('custom_field_values', models.JSONField(blank=True, default=dict)),
                ('no_serial_reason', models.CharField(blank=True, max_length=300)),
                ('line_number', models.PositiveIntegerField(default=1)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('gate_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='receiving.gatein')),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gate_in_lines', to='catalogue.itemtype')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
                ('owner_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gate_in_lines', to='network.client')),
            ],
            options={
                'ordering': ('line_number', 'id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GateInReel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drum_number', models.CharField(max_length=100)),
                ('length', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reels', to='receiving.gateinline')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
            ],
            options={
                'ordering': ('drum_number',),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GateInSerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=150)),
                ('asset_tag', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(choices=[('MANUFACTURER', 'Manufacturer serial'), ('INTERNAL', 'Internally generated asset tag')], default='MANUFACTURER', max_length=20)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serials', to='receiving.gateinline')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
            ],
            options={
                'ordering': ('serial_number',),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='gatein',
            index=models.Index(fields=['organization', 'status', '-received_at'], name='receiving_g_organiz_94e881_idx'),
        ),
        migrations.AddIndex(
            model_name='gatein',
            index=models.Index(fields=['organization', 'source_type'], name='receiving_g_organiz_bbdde4_idx'),
        ),
        migrations.AddIndex(
            model_name='gatein',
            index=models.Index(fields=['organization', 'origin_site'], name='receiving_g_organiz_69aa8f_idx'),
        ),
        migrations.AddConstraint(
            model_name='gatein',
            constraint=models.UniqueConstraint(condition=models.Q(('number__gt', '')), fields=('organization', 'number'), name='uniq_gate_in_number_per_org'),
        ),
        migrations.AddConstraint(
            model_name='gatein',
            constraint=models.UniqueConstraint(condition=models.Q(('client_uuid__isnull', False)), fields=('organization', 'client_uuid'), name='uniq_gate_in_client_uuid_per_org'),
        ),
        migrations.AddConstraint(
            model_name='gatein',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('number', ''), ('status', 'DRAFT')), models.Q(models.Q(('status', 'DRAFT'), _negated=True), models.Q(('number', ''), _negated=True)), _connector='OR'), name='posted_gate_in_has_a_number'),
        ),
        migrations.AddConstraint(
            model_name='gateinline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner_client__isnull', False), ('owner_type', 'CLIENT')), models.Q(('owner_client__isnull', True), ('owner_type', 'OWN')), _connector='OR'), name='client_owned_line_names_its_client'),
        ),
        migrations.AddConstraint(
            model_name='gateinreel',
            constraint=models.UniqueConstraint(fields=('line', 'drum_number'), name='uniq_drum_per_gate_in_line'),
        ),
        migrations.AddConstraint(
            model_name='gateinreel',
            constraint=models.CheckConstraint(condition=models.Q(('length__gt', 0)), name='gate_in_reel_has_a_length'),
        ),
        migrations.AddConstraint(
            model_name='gateinserial',
            constraint=models.UniqueConstraint(fields=('line', 'serial_number'), name='uniq_serial_per_gate_in_line'),
        ),
    ]
