# Generated by Django 5.2.17 on 2026-08-21 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0002_enable_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gatein',
            name='returned_by',
            field=models.ForeignKey(blank=True, help_text='Who is handing the material back (required for a return from site).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gate_ins_returned', to=settings.AUTH_USER_MODEL),
        ),
    ]
