# Generated by Django 5.2.17 on 2026-09-18 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_project_client_and_more'),
        ('receiving', '0003_gatein_returned_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatein',
            name='origin_site',
            field=models.ForeignKey(blank=True, help_text="Where the material came off. Required for a recovery (D5); worth recording on a return so the site's reconciliation can see it (H4).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recoveries', to='network.site'),
        ),
    ]
