# Generated by Django 5.2.17 on 2026-09-18 20:22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0004_alter_gatein_origin_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateinline',
            name='declared_unit_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="The client's stated value per unit, excluding VAT. Client-owned lines only — leave it empty when the issue note gives no figure.", max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
