# Generated by Django 5.2.17 on 2026-10-03 06:56

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_release_scan_required'),
        ('receiving', '0005_gate_in_line_declared_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gateinline',
            name='box_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='gateinserial',
            name='box_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='GateInBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=64)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('parent_key', models.CharField(blank=True, max_length=64)),
                ('label_text', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('gate_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_in_boxes', to='receiving.gatein')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
            ],
            options={
                'ordering': ('id',),
                'constraints': [models.UniqueConstraint(fields=('gate_in', 'key'), name='uniq_box_key_per_gate_in')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
