# Generated by Django 5.2.17 on 2026-10-03 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_subcontractor_rls'),
        ('receiving', '0007_enable_rls_gate_in_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatein',
            name='for_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gate_ins_for', to='network.site'),
        ),
        migrations.AddField(
            model_name='gateinline',
            name='for_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gate_in_lines_for', to='network.site'),
        ),
    ]
