# Generated by Django 5.2.17 on 2026-10-09 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_supplier_register'),
        ('receiving', '0008_earmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatein',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gate_ins', to='network.supplier'),
        ),
    ]
