# Generated by Django 5.2.17 on 2026-08-21 21:17

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0002_enable_rls'),
        ('core', '0009_alter_auditlog_action'),
        ('dispatch', '0002_enable_rls'),
        ('stock', '0004_count_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustodyTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Awaiting acknowledgement'), ('ACKNOWLEDGED', 'Acknowledged'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('number', models.CharField(blank=True, db_index=True, max_length=50)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('declined_reason', models.CharField(blank=True, max_length=500)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('from_holder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custody_transfers_out', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('to_holder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custody_transfers_in', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CustodyTransferLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('uom', models.CharField(max_length=20)),
                ('condition', models.CharField(blank=True, max_length=20)),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogue.itemtype')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
                ('reel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='stock.reel')),
                ('serial_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='stock.serialunit')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='custody.custodytransfer')),
            ],
            options={
                'ordering': ('id',),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CustodyExpectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('returned_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('expected_return_date', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Outstanding'), ('RETURNED', 'Returned'), ('OVERDUE', 'Overdue'), ('WRITTEN_OFF', 'Written off')], db_index=True, default='OPEN', max_length=20)),
                ('reminded_holder_at', models.DateTimeField(blank=True, null=True)),
                ('reminded_supervisor_at', models.DateTimeField(blank=True, null=True)),
                ('reminded_owner_at', models.DateTimeField(blank=True, null=True)),
                ('written_off_reason', models.CharField(blank=True, max_length=500)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('gate_out_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custody_expectations', to='dispatch.gateoutline')),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custody_expectations', to=settings.AUTH_USER_MODEL)),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custody_expectations', to='catalogue.itemtype')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
                ('reel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custody_expectations', to='stock.reel')),
                ('serial_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custody_expectations', to='stock.serialunit')),
            ],
            options={
                'ordering': ('expected_return_date', 'id'),
                'indexes': [models.Index(fields=['organization', 'holder', 'status'], name='custody_cus_organiz_19f365_idx'), models.Index(fields=['organization', 'status', 'expected_return_date'], name='custody_cus_organiz_593718_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('returned_quantity__gte', 0), ('returned_quantity__lte', models.F('quantity'))), name='returned_quantity_is_within_what_was_issued')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='custodytransfer',
            constraint=models.CheckConstraint(condition=models.Q(('from_holder', models.F('to_holder')), _negated=True), name='custody_transfer_changes_holder'),
        ),
        migrations.AddConstraint(
            model_name='custodytransfer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'ACKNOWLEDGED'), _negated=True), ('acknowledged_at__isnull', False), _connector='OR'), name='acknowledged_transfer_records_when'),
        ),
    ]
