# Generated by Django 5.2.17 on 2026-08-21 19:33

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_alter_auditlog_actor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('LOCATION', 'Yard, store, vehicle or quarantine'), ('PERSON', "Held in someone's custody"), ('SITE', 'Installed at a site'), ('CLIENT', 'Returned to a client'), ('EXTERNAL', 'Supplier or client-issuing store'), ('CONSUMED', 'Used up on site'), ('SCRAP', 'Disposed of')], db_index=True, max_length=20)),
                ('label', models.CharField(max_length=200)),
            ],
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('type', models.CharField(choices=[('YARD', 'Yard'), ('STORE', 'Store within a yard'), ('VEHICLE', 'Vehicle'), ('QUARANTINE', 'Quarantine')], max_length=20)),
                ('vehicle_reg', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='locations.location')),
            ],
            options={
                'ordering': ('name',),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
