# Generated by Django 5.2.17 on 2026-08-21 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_alter_auditlog_actor'),
        ('locations', '0001_initial'),
        ('network', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stocknode',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nodes', to='network.client'),
        ),
        migrations.AddField(
            model_name='stocknode',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocknode',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='node', to='locations.location'),
        ),
        migrations.AddField(
            model_name='stocknode',
            name='organization',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
        migrations.AddField(
            model_name='stocknode',
            name='site',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='node', to='network.site'),
        ),
        migrations.AddField(
            model_name='stocknode',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_node', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('organization', 'parent', 'name'), name='uniq_location_name_per_parent'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type', 'YARD'), _negated=True), ('parent__isnull', True), _connector='OR'), name='a_yard_has_no_parent'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type', 'STORE'), _negated=True), ('parent__isnull', False), _connector='OR'), name='a_store_sits_inside_a_yard'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type', 'VEHICLE'), _negated=True), models.Q(('vehicle_reg', ''), _negated=True), _connector='OR'), name='a_vehicle_has_a_registration'),
        ),
        migrations.AddIndex(
            model_name='stocknode',
            index=models.Index(fields=['organization', 'type'], name='locations_s_organiz_e81c9f_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocknode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type', 'LOCATION'), ('location__isnull', False), ('user__isnull', True), ('site__isnull', True), ('client__isnull', True)), models.Q(('type', 'PERSON'), ('user__isnull', False), ('location__isnull', True), ('site__isnull', True), ('client__isnull', True)), models.Q(('type', 'SITE'), ('site__isnull', False), ('location__isnull', True), ('user__isnull', True), ('client__isnull', True)), models.Q(('type', 'CLIENT'), ('client__isnull', False), ('location__isnull', True), ('user__isnull', True), ('site__isnull', True)), models.Q(('type', 'EXTERNAL'), ('location__isnull', True), ('user__isnull', True), ('site__isnull', True)), models.Q(('type__in', ['CONSUMED', 'SCRAP']), ('location__isnull', True), ('user__isnull', True), ('site__isnull', True), ('client__isnull', True)), _connector='OR'), name='stock_node_arity_matches_its_type'),
        ),
        migrations.AddConstraint(
            model_name='stocknode',
            constraint=models.UniqueConstraint(condition=models.Q(('type__in', ['CONSUMED', 'SCRAP'])), fields=('organization', 'type'), name='uniq_system_node_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='stocknode',
            constraint=models.UniqueConstraint(condition=models.Q(('client__isnull', True), ('type', 'EXTERNAL')), fields=('organization',), name='uniq_generic_external_node_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='stocknode',
            constraint=models.UniqueConstraint(condition=models.Q(('client__isnull', False), ('type', 'EXTERNAL')), fields=('organization', 'client'), name='uniq_client_external_node_per_organization'),
        ),
    ]
