# Generated by Django 5.2.17 on 2026-09-18 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_workorder_becomes_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='network.client'),
        ),
        migrations.AlterField(
            model_name='project',
            name='closed_with_unreconciled',
            field=models.BooleanField(default=False, help_text='Closed while material remained unreconciled, with a reason.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sites',
            field=models.ManyToManyField(blank=True, related_name='projects', to='network.site'),
        ),
    ]
