# Generated by Django 5.2.17 on 2026-09-18 19:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_organizationsettings_sms_credit_balance_and_more'),
        ('network', '0004_alter_project_client_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='project',
            name='closed_project_has_a_closing_time',
        ),
        migrations.AddField(
            model_name='project',
            name='contract_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='What the client pays, excluding VAT.', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='project',
            name='cost_budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='What the manager may spend to deliver it, excluding VAT.', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='The project manager. Approves material leaving for this project, and is the only approver on it (O6).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_managed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='po_number',
            field=models.CharField(blank=True, db_index=True, help_text="The client's purchase order number. One PO is one project (D21).", max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='starts_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='target_completion_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(condition=models.Q(('po_number__gt', '')), fields=('organization', 'po_number'), name='uniq_project_po_number_per_org'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('closed_at__isnull', True), ('status', 'OPEN')), models.Q(('closed_at__isnull', False), ('status__in', ('CLOSED', 'CANCELLED'))), _connector='OR'), name='closed_project_has_a_closing_time'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('po_number', ''), models.Q(('contract_value__isnull', False), ('cost_budget__isnull', False), ('manager__isnull', False)), _connector='OR'), name='a_po_project_is_fully_specified'),
        ),
    ]
