# Generated by Django 5.2.17 on 2026-09-18 19:46

import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_organizationsettings_sms_credit_balance_and_more'),
        ('network', '0005_project_purchase_order_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(help_text="The client's variation or amendment reference.", max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('value_delta', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Change to the contract value, excluding VAT. May be negative.', max_digits=14)),
                ('budget_delta', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Change to the cost budget, excluding VAT. May be negative.', max_digits=14)),
                ('effective_on', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', "Awaiting the owner's decision"), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.CharField(blank=True, max_length=500)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variations', to='network.project')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variations_raised', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('effective_on', 'id'),
                'indexes': [models.Index(fields=['organization', 'project', 'status'], name='network_pro_organiz_e04fa7_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'project', 'reference'), name='uniq_variation_ref_per_project'), models.CheckConstraint(condition=models.Q(models.Q(('decided_at__isnull', True), ('status', 'PENDING')), models.Q(('decided_at__isnull', False), ('status__in', ('APPROVED', 'REJECTED'))), _connector='OR'), name='a_decided_variation_records_when')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
