# Generated by Django 5.2.17 on 2026-10-09 15:49

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_organizationsettings_clock_accuracy_cap_m_and_more'),
        ('network', '0009_subcontractor_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='area_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='site',
            name='radius_m',
            field=models.PositiveIntegerField(default=200, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.CheckConstraint(condition=models.Q(('latitude__isnull', True), models.Q(('latitude__gte', -90), ('latitude__lte', 90)), _connector='OR'), name='site_latitude_in_range'),
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.CheckConstraint(condition=models.Q(('longitude__isnull', True), models.Q(('longitude__gte', -180), ('longitude__lte', 180)), _connector='OR'), name='site_longitude_in_range'),
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('latitude__isnull', True), ('longitude__isnull', True)), models.Q(('latitude__isnull', False), ('longitude__isnull', False)), _connector='OR'), name='site_coordinates_both_or_neither'),
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.CheckConstraint(condition=models.Q(('radius_m__gte', 20), ('radius_m__lte', 2000)), name='site_radius_between_20_and_2000_m'),
        ),
    ]
