# Generated by Django 5.2.17 on 2026-08-22 07:58

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0002_enable_rls'),
        ('core', '0010_attachment_audit_actions'),
        ('dispatch', '0003_gate_out_line_no_serial_reason'),
        ('locations', '0003_enable_rls'),
        ('network', '0002_enable_rls'),
        ('stock', '0005_stockmovement_from_condition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Awaiting approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DISPOSED', 'Disposed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', editable=False, max_length=20)),
                ('method', models.CharField(choices=[('SCRAP_DEALER', 'Sold or given to a scrap dealer'), ('LICENSED_HANDLER', 'Collected by a licensed e-waste handler'), ('DESTROYED_ON_SITE', 'Destroyed on our premises'), ('RETURNED_TO_SUPPLIER', 'Returned to the supplier'), ('OTHER', 'Other — see the note')], max_length=30)),
                ('handler_name', models.CharField(blank=True, max_length=200)),
                ('handler_reference', models.CharField(blank=True, max_length=100)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('disposed_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.CharField(blank=True, max_length=500)),
                ('cancel_reason', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('client_uuid', models.UUIDField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('disposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disposals', to='locations.location')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DisposalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('uom', models.CharField(max_length=20)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('USED_SERVICEABLE', 'Used — serviceable'), ('FAULTY', 'Faulty'), ('DAMAGED', 'Damaged'), ('SCRAP', 'Scrap')], default='SCRAP', max_length=20)),
                ('owner_type', models.CharField(choices=[('OWN', 'Own stock'), ('CLIENT', 'Client-owned (consignment)')], default='OWN', max_length=10)),
                ('written_off_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('line_number', models.PositiveIntegerField(default=1)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('disposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='disposition.disposal')),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disposal_lines', to='catalogue.itemtype')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
                ('owner_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disposal_lines', to='network.client')),
                ('reel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='stock.reel')),
                ('serial_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='stock.serialunit')),
            ],
            options={
                'ordering': ('line_number', 'id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Disposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Awaiting approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', editable=False, max_length=20)),
                ('decision', models.CharField(choices=[('REPAIR', 'Send for repair'), ('RESTORE_TO_SERVICEABLE', 'Restore to serviceable'), ('RETURN_TO_CLIENT', 'Return to the client'), ('SCRAP', 'Scrap')], max_length=30)),
                ('reason', models.CharField(max_length=500)),
                ('vendor_name', models.CharField(blank=True, max_length=200)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.CharField(blank=True, max_length=500)),
                ('cancel_reason', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('client_uuid', models.UUIDField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('disposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispositions', to='disposition.disposal')),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispositions', to='locations.location')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inbound_dispositions', to='locations.location')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DispositionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('uom', models.CharField(max_length=20)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('USED_SERVICEABLE', 'Used — serviceable'), ('FAULTY', 'Faulty'), ('DAMAGED', 'Damaged'), ('SCRAP', 'Scrap')], default='FAULTY', max_length=20)),
                ('to_condition', models.CharField(blank=True, choices=[('NEW', 'New'), ('USED_SERVICEABLE', 'Used — serviceable'), ('FAULTY', 'Faulty'), ('DAMAGED', 'Damaged'), ('SCRAP', 'Scrap')], max_length=20)),
                ('owner_type', models.CharField(choices=[('OWN', 'Own stock'), ('CLIENT', 'Client-owned (consignment)')], default='OWN', max_length=10)),
                ('line_number', models.PositiveIntegerField(default=1)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('disposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='disposition.disposition')),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disposition_lines', to='catalogue.itemtype')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
                ('owner_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disposition_lines', to='network.client')),
                ('reel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='stock.reel')),
                ('serial_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='stock.serialunit')),
            ],
            options={
                'ordering': ('line_number', 'id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ClientReturnAck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_ref', models.CharField(max_length=200)),
                ('acknowledged_at', models.DateTimeField()),
                ('acknowledged_by_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('gate_out', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='client_return_ack', to='dispatch.gateout')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-acknowledged_at', '-id'),
                'indexes': [models.Index(fields=['organization', 'acknowledged_at'], name='disposition_organiz_d43241_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='disposal',
            index=models.Index(fields=['organization', 'status'], name='disposition_organiz_52e40c_idx'),
        ),
        migrations.AddConstraint(
            model_name='disposal',
            constraint=models.UniqueConstraint(condition=models.Q(('number__gt', '')), fields=('organization', 'number'), name='uniq_disposal_number_per_org'),
        ),
        migrations.AddConstraint(
            model_name='disposal',
            constraint=models.UniqueConstraint(condition=models.Q(('client_uuid__isnull', False)), fields=('organization', 'client_uuid'), name='uniq_disposal_client_uuid_per_org'),
        ),
        migrations.AddConstraint(
            model_name='disposal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('disposed_at__isnull', False), ('status', 'DISPOSED')), models.Q(('status', 'DISPOSED'), _negated=True), _connector='OR'), name='a_completed_disposal_records_when'),
        ),
        migrations.AddConstraint(
            model_name='disposalline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner_client__isnull', False), ('owner_type', 'CLIENT')), models.Q(('owner_client__isnull', True), ('owner_type', 'OWN')), _connector='OR'), name='client_owned_disposal_line_names_its_client'),
        ),
        migrations.AddIndex(
            model_name='disposition',
            index=models.Index(fields=['organization', 'status', 'decision'], name='disposition_organiz_f30120_idx'),
        ),
        migrations.AddConstraint(
            model_name='disposition',
            constraint=models.UniqueConstraint(condition=models.Q(('number__gt', '')), fields=('organization', 'number'), name='uniq_disposition_number_per_org'),
        ),
        migrations.AddConstraint(
            model_name='disposition',
            constraint=models.UniqueConstraint(condition=models.Q(('client_uuid__isnull', False)), fields=('organization', 'client_uuid'), name='uniq_disposition_client_uuid_per_org'),
        ),
        migrations.AddConstraint(
            model_name='dispositionline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner_client__isnull', False), ('owner_type', 'CLIENT')), models.Q(('owner_client__isnull', True), ('owner_type', 'OWN')), _connector='OR'), name='client_owned_disposition_line_names_its_client'),
        ),
    ]
