# Generated by Django 5.2.17 on 2026-09-18 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposition', '0002_enable_rls'),
        ('network', '0009_subcontractor_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposal',
            name='project',
            field=models.ForeignKey(blank=True, help_text='The project this write-off is charged to, if any (O10).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disposals', to='network.project'),
        ),
    ]
