# Generated by Django 5.2.17 on 2026-10-09 15:55

import core.immutability
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvals', '0006_request_required_permission'),
        ('core', '0017_finance_settings_attachment_fields'),
        ('locations', '0003_enable_rls'),
        ('network', '0009_subcontractor_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PENDING', 'Waiting on approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='OPEN', max_length=20)),
                ('formed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date',),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_date', models.DateField(db_index=True)),
                ('clock_in_at', models.DateTimeField()),
                ('clock_in_received_at', models.DateTimeField()),
                ('in_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('in_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('in_accuracy_m', models.FloatField(blank=True, null=True)),
                ('in_distance_m', models.FloatField(blank=True, null=True)),
                ('clock_out_at', models.DateTimeField(blank=True, null=True)),
                ('clock_out_received_at', models.DateTimeField(blank=True, null=True)),
                ('out_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('out_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('out_accuracy_m', models.FloatField(blank=True, null=True)),
                ('out_distance_m', models.FloatField(blank=True, null=True)),
                ('closed_by', models.CharField(blank=True, choices=[('PERSON', 'The person'), ('NEXT_CLOCK_IN', 'Their next clock-in'), ('AUTO', 'Closed automatically')], default='', max_length=20)),
                ('in_client_uuid', models.UUIDField(blank=True, null=True)),
                ('out_client_uuid', models.UUIDField(blank=True, null=True)),
                ('in_checked_area', models.JSONField(blank=True, null=True)),
                ('area_changed', models.BooleanField(default=False)),
                ('added_reason', models.CharField(blank=True, max_length=500)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('approval_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_sessions', to='approvals.approvalrequest')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_sessions', to='locations.location')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_sessions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_sessions', to='network.project')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_sessions', to='network.site')),
                ('work_day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='attendance.workday')),
            ],
            options={
                'ordering': ('clock_in_at',),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='WorkSessionCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('EDIT', 'Edit an existing session'), ('ADD', 'Add a missing session')], max_length=10)),
                ('original_in_at', models.DateTimeField(blank=True, null=True)),
                ('original_out_at', models.DateTimeField(blank=True, null=True)),
                ('corrected_in_at', models.DateTimeField(blank=True, null=True)),
                ('corrected_out_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(max_length=500)),
                ('made_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='locations.location')),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
                ('rejected_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='approvals.approvalrequest')),
                ('reopened_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='approvals.approvalrequest')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='attendance.worksession')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='network.site')),
                ('work_day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='attendance.workday')),
            ],
            options={
                'ordering': ('made_at', 'pk'),
            },
            bases=(core.immutability.AppendOnlyModel, models.Model),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='workday',
            constraint=models.UniqueConstraint(fields=('organization', 'person', 'date'), name='uniq_work_day_per_person_date'),
        ),
        migrations.AddIndex(
            model_name='worksession',
            index=models.Index(fields=['organization', 'person', 'local_date'], name='attendance__organiz_5726b2_idx'),
        ),
        migrations.AddConstraint(
            model_name='worksession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('site__isnull', False), ('location__isnull', True)), models.Q(('site__isnull', True), ('location__isnull', False)), _connector='OR'), name='work_session_exactly_one_place'),
        ),
        migrations.AddConstraint(
            model_name='worksession',
            constraint=models.CheckConstraint(condition=models.Q(('clock_out_at__isnull', True), ('clock_out_at__gte', models.F('clock_in_at')), _connector='OR'), name='work_session_out_not_before_in'),
        ),
        migrations.AddConstraint(
            model_name='worksession',
            constraint=models.UniqueConstraint(condition=models.Q(('clock_out_at__isnull', True)), fields=('organization', 'person'), name='uniq_open_work_session_per_person'),
        ),
        migrations.AddConstraint(
            model_name='worksession',
            constraint=models.UniqueConstraint(condition=models.Q(('in_client_uuid__isnull', False)), fields=('organization', 'in_client_uuid'), name='uniq_work_session_in_uuid_per_org'),
        ),
        migrations.AddConstraint(
            model_name='worksession',
            constraint=models.UniqueConstraint(condition=models.Q(('out_client_uuid__isnull', False)), fields=('organization', 'out_client_uuid'), name='uniq_work_session_out_uuid_per_org'),
        ),
        migrations.AddConstraint(
            model_name='worksessioncorrection',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'EDIT'), ('session__isnull', False), ('site__isnull', True), ('location__isnull', True)), models.Q(('kind', 'ADD'), ('session__isnull', True), models.Q(models.Q(('site__isnull', False), ('location__isnull', True)), models.Q(('site__isnull', True), ('location__isnull', False)), _connector='OR')), _connector='OR'), name='work_correction_kind_matches_target'),
        ),
    ]
