# Generated by Django 5.2.17 on 2026-08-22 09:04

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0010_attachment_audit_actions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_uuid', models.UUIDField()),
                ('operation', models.CharField(choices=[('GATE_IN', 'Receive a delivery'), ('GATE_OUT_REQUEST', 'Request material'), ('GATE_OUT_RELEASE', 'Release an already-approved pass')], max_length=30)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('REJECTED', 'Rejected')], default='APPLIED', max_length=20)),
                ('document_type', models.CharField(blank=True, max_length=100)),
                ('document_id', models.CharField(blank=True, max_length=64)),
                ('document_number', models.CharField(blank=True, max_length=50)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SyncException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved'), ('DISCARDED', 'Discarded')], db_index=True, default='OPEN', max_length=20)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('reason', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('resolution', models.CharField(blank=True, max_length=500)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('replacement_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replaces', to='sync.syncsubmission')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exception', to='sync.syncsubmission')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='syncsubmission',
            index=models.Index(fields=['organization', 'status'], name='sync_syncsu_organiz_701b59_idx'),
        ),
        migrations.AddIndex(
            model_name='syncsubmission',
            index=models.Index(fields=['organization', 'operation'], name='sync_syncsu_organiz_37d2ae_idx'),
        ),
        migrations.AddConstraint(
            model_name='syncsubmission',
            constraint=models.UniqueConstraint(fields=('organization', 'client_uuid'), name='uniq_sync_submission_per_org'),
        ),
        migrations.AddIndex(
            model_name='syncexception',
            index=models.Index(fields=['organization', 'status'], name='sync_syncex_organiz_5c9f1a_idx'),
        ),
        migrations.AddConstraint(
            model_name='syncexception',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('resolved_at__isnull', True), ('status', 'OPEN')), models.Q(('status', 'OPEN'), _negated=True), _connector='OR'), name='an_open_sync_exception_is_not_resolved'),
        ),
    ]
