# Generated by Django 5.2.17 on 2026-10-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0003_finance_sync_operations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncsubmission',
            name='operation',
            field=models.CharField(choices=[('GATE_IN', 'Receive a delivery'), ('GATE_OUT_REQUEST', 'Request material'), ('GATE_OUT_RELEASE', 'Release an already-approved pass'), ('EXPENSE', 'Record an expense'), ('ALLOWANCE_REQUEST', 'Request an allowance or float'), ('CASUAL', 'Register a casual'), ('SUPPLIER', 'Add a supplier')], max_length=30),
        ),
    ]
