# Generated by Django 5.2.17 on 2026-09-18 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_work_order_becomes_project'),
        ('network', '0004_alter_project_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='network.project'),
        ),
    ]
