# Generated by Django 5.2.17 on 2026-09-18 20:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_organizationsettings_sms_credit_balance_and_more'),
        ('jobs', '0004_alter_job_project'),
        ('network', '0009_subcontractor_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='agreed_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='What was agreed with the contractor for this job, excluding VAT.', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='job',
            name='delivery_mode',
            field=models.CharField(choices=[('IN_HOUSE', 'Delivered by our own crews'), ('SUBCONTRACTED', 'Delivered by a subcontractor')], default='IN_HOUSE', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='subcontractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='network.subcontractor'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('agreed_price__isnull', True), ('delivery_mode', 'IN_HOUSE'), ('subcontractor__isnull', True)), models.Q(('agreed_price__isnull', False), ('delivery_mode', 'SUBCONTRACTED'), ('subcontractor__isnull', False)), _connector='OR'), name='delivery_mode_and_its_cost_agree'),
        ),
    ]
