# Generated by Django 5.2.17 on 2026-09-18 21:25

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_organizationsettings_project_release_notify_above'),
        ('jobs', '0005_job_delivery_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobLabour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_date', models.DateField()),
                ('days', models.DecimalField(decimal_places=1, help_text='Days worked, to one decimal place, so half days work.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))])),
                ('day_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rate_source', models.CharField(choices=[('USER', "The person's own rate"), ('ROLE', 'The rate on a role they hold'), ('NONE', 'No rate applies — uncosted')], default='NONE', max_length=10)),
                ('overlaps_day', models.BooleanField(default=False)),
                ('closeout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labour', to='jobs.jobcloseout')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labour', to='jobs.job')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='labour_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('work_date', 'id'),
                'indexes': [models.Index(fields=['organization', 'person', 'work_date'], name='jobs_joblab_organiz_ada698_idx'), models.Index(fields=['organization', 'overlaps_day'], name='jobs_joblab_organiz_30eaf9_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'job', 'person', 'work_date'), name='one_labour_entry_per_person_per_day_per_job'), models.CheckConstraint(condition=models.Q(models.Q(('day_rate__isnull', True), ('rate_source', 'NONE')), models.Q(('day_rate__isnull', False), models.Q(('rate_source', 'NONE'), _negated=True)), _connector='OR'), name='a_costed_labour_entry_says_where_its_rate_came_from')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
