# Generated by Django 5.2.17 on 2026-09-18 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_organizationsettings_project_release_notify_above'),
        ('jobs', '0007_job_labour_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcloseout',
            name='cost_acceptance',
            field=models.CharField(choices=[('NOT_REQUIRED', 'No project manager to accept it'), ('PENDING', 'Waiting on the project manager'), ('ACCEPTED', 'Accepted by the project manager'), ('QUERIED', 'Queried — a corrected closeout is wanted')], db_index=True, default='NOT_REQUIRED', max_length=20),
        ),
        migrations.AddField(
            model_name='jobcloseout',
            name='cost_decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcloseout',
            name='cost_decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobcloseout',
            name='cost_query_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddIndex(
            model_name='jobcloseout',
            index=models.Index(fields=['organization', 'cost_acceptance'], name='jobs_jobclo_organiz_a52552_idx'),
        ),
    ]
