# Generated by Django 5.2.17 on 2026-10-09 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercials', '0008_stage2_models'),
        ('core', '0019_stage2_models'),
        ('jobs', '0008_closeout_cost_acceptance'),
        ('network', '0009_subcontractor_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='over_contract_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='job',
            name='subcontract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='commercials.subcontract'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('subcontract__isnull', True), ('delivery_mode', 'SUBCONTRACTED'), _connector='OR'), name='only_a_subcontracted_job_has_a_subcontract'),
        ),
    ]
