# Generated by Django 5.2.17 on 2026-08-21 19:29

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_alter_auditlog_actor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('criticality', models.CharField(choices=[('NONE', 'None'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='NONE', help_text='Drives which role must approve a gate-out containing this material.', max_length=10)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalogue.itemcategory')),
            ],
            options={
                'verbose_name_plural': 'item categories',
                'ordering': ('name',),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CategoryCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=100)),
                ('key', models.SlugField(help_text='Stable identifier used in stored values. Immutable once set.', max_length=100)),
                ('field_type', models.CharField(choices=[('TEXT', 'Text'), ('NUMBER', 'Number'), ('DATE', 'Date'), ('DROPDOWN', 'Dropdown'), ('BOOLEAN', 'Yes / no')], max_length=20)),
                ('required_at_gate_in', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, default=list, help_text='Choices, for a dropdown field.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='catalogue.itemcategory')),
            ],
            options={
                'ordering': ('order', 'label'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('default_tracking_mode', models.CharField(choices=[('SERIALIZED', 'Serialized — each unit individually identified'), ('BULK', 'Bulk — a counted quantity'), ('REEL', 'Reel — a measured length on a numbered drum')], default='BULK', max_length=20)),
                ('uom', models.CharField(default='ea', help_text='Unit of measure: ea, m, kg, roll.', max_length=20)),
                ('is_returnable', models.BooleanField(default=False)),
                ('default_return_days', models.PositiveIntegerField(blank=True, null=True)),
                ('min_stock_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_types', to='catalogue.itemcategory')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
            ],
            options={
                'ordering': ('name',),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='itemcategory',
            constraint=models.UniqueConstraint(fields=('organization', 'parent', 'name'), name='uniq_category_name_per_parent'),
        ),
        migrations.AddConstraint(
            model_name='categorycustomfield',
            constraint=models.UniqueConstraint(fields=('category', 'key'), name='uniq_custom_field_key_per_category'),
        ),
        migrations.AddIndex(
            model_name='itemtype',
            index=models.Index(fields=['organization', 'is_archived'], name='catalogue_i_organiz_c75a23_idx'),
        ),
        migrations.AddConstraint(
            model_name='itemtype',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_item_type_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='itemtype',
            constraint=models.UniqueConstraint(condition=models.Q(('code__gt', '')), fields=('organization', 'code'), name='uniq_item_type_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='itemtype',
            constraint=models.CheckConstraint(condition=models.Q(('is_returnable', False), ('default_return_days__isnull', False), _connector='OR'), name='returnable_item_has_a_return_period'),
        ),
    ]
