# Generated by Django 5.2.17 on 2026-10-09 07:40

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def submitted_to_pending_pm(apps, schema_editor):  # type: ignore[no-untyped-def]
    """In-flight O16 expenses wait on the project manager, as they did (§4.17.11).

    Only the status moves. Their ``ApprovalRequest`` rows need the engine's
    finance branch, so T15.2 adds a follow-up migration that creates them;
    until then these rows are plain PENDING_PM with no request, and the legacy
    ``decide_expense`` still works on them. APPROVED and REJECTED rows are
    untouched and still counted.
    """
    from core.tenancy import tenant_context

    Organization = apps.get_model("core", "Organization")
    ProjectExpense = apps.get_model("commercials", "ProjectExpense")
    # Per tenant: the table is under FORCE row-level security (§2.3), so an
    # update with no organization in context would match nothing.
    for organization in Organization.objects.all():
        with tenant_context(organization):
            ProjectExpense.objects.filter(
                organization=organization, status="SUBMITTED"
            ).update(status="PENDING_PM")


class Migration(migrations.Migration):

    dependencies = [
        ('commercials', '0002_enable_rls'),
        ('core', '0016_serial_corrected_audit_action'),
        ('jobs', '0008_closeout_cost_acceptance'),
        ('network', '0009_subcontractor_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=50)),
                ('type', models.CharField(choices=[('FLOAT', 'Float'), ('TRANSPORT', 'Transport'), ('NIGHT_OUT', 'Night out'), ('TEAM_ALLOWANCE', 'Team allowance'), ('OTHER', 'Other')], max_length=20)),
                ('transport_scope', models.CharField(blank=True, choices=[('WITHIN_NAIROBI', 'Within Nairobi'), ('OUTSIDE_NAIROBI', 'Outside Nairobi')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='The whole request, not per day. Excluding VAT (D24).', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('PENDING_PM', 'Waiting on the project manager'), ('PENDING_FINANCE', 'Waiting on Finance'), ('APPROVED', 'Approved — counts against the project'), ('PAID', 'Paid'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING_PM', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.CharField(blank=True, max_length=500)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('returned_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('client_uuid', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-from_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Casual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('id_number', models.CharField(max_length=40)),
                ('id_number_key', models.CharField(editable=False, max_length=40)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('client_uuid', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseCasualLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('days', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
            ],
            options={
                'ordering': ('id',),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='projectexpense',
            managers=[
            ],
        ),
        migrations.RemoveConstraint(
            model_name='projectexpense',
            name='a_decided_expense_records_when',
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='kind',
            field=models.CharField(choices=[('GENERAL', 'General'), ('FUEL', 'Fuel — needs the vehicle registration'), ('CASUAL_LABOUR', 'Casual labour — needs the casuals and days')], default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='client_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='litres',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='photos_expected',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='scope_of_work',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='network.site'),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='vehicle_reg',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='projectexpense',
            name='status',
            field=models.CharField(choices=[('PENDING_PM', 'Waiting on the project manager'), ('PENDING_FINANCE', 'Waiting on Finance'), ('APPROVED', 'Approved — counts against the project'), ('PAID', 'Paid'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING_PM', max_length=20),
        ),
        # Must run before the new a_decided_expense_records_when CHECK is added
        # (last operation), which does not know SUBMITTED.
        migrations.RunPython(submitted_to_pending_pm, migrations.RunPython.noop),
        migrations.AddField(
            model_name='allowancerequest',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allowancerequest',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allowancerequest',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allowancerequest',
            name='organization',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
        migrations.AddField(
            model_name='allowancerequest',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allowancerequest',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allowance_requests', to='network.project'),
        ),
        migrations.AddField(
            model_name='allowancerequest',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allowances_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allowancerequest',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allowance_requests', to='network.site'),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='float_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='commercials.allowancerequest'),
        ),
        migrations.AddConstraint(
            model_name='projectexpense',
            constraint=models.UniqueConstraint(condition=models.Q(('client_uuid__isnull', False)), fields=('organization', 'client_uuid'), name='uniq_expense_client_uuid_per_org'),
        ),
        migrations.AddConstraint(
            model_name='projectexpense',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decided_at__isnull', True), ('status__in', ('PENDING_PM', 'PENDING_FINANCE'))), models.Q(('decided_at__isnull', False), ('status__in', ('APPROVED', 'PAID', 'REJECTED'))), _connector='OR'), name='a_decided_expense_records_when'),
        ),
        migrations.AddField(
            model_name='casual',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='casual',
            name='organization',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
        migrations.AddField(
            model_name='casual',
            name='registered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expensecasualline',
            name='casual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='commercials.casual'),
        ),
        migrations.AddField(
            model_name='expensecasualline',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expensecasualline',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='casual_lines', to='commercials.projectexpense'),
        ),
        migrations.AddField(
            model_name='expensecasualline',
            name='organization',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
        migrations.AddIndex(
            model_name='allowancerequest',
            index=models.Index(fields=['organization', 'status'], name='commercials_organiz_73e4c9_idx'),
        ),
        migrations.AddIndex(
            model_name='allowancerequest',
            index=models.Index(fields=['organization', 'recorded_by', 'type'], name='commercials_organiz_f8c5af_idx'),
        ),
        migrations.AddConstraint(
            model_name='allowancerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('organization', 'number'), name='uniq_allowance_number_per_org'),
        ),
        migrations.AddConstraint(
            model_name='allowancerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('client_uuid__isnull', False)), fields=('organization', 'client_uuid'), name='uniq_allowance_client_uuid_per_org'),
        ),
        migrations.AddConstraint(
            model_name='allowancerequest',
            constraint=models.CheckConstraint(condition=models.Q(('to_date__gte', models.F('from_date'))), name='an_allowance_ends_on_or_after_it_starts'),
        ),
        migrations.AddConstraint(
            model_name='allowancerequest',
            constraint=models.CheckConstraint(condition=models.Q(('type', 'TRANSPORT'), ('transport_scope', ''), _connector='OR'), name='only_transport_has_a_scope'),
        ),
        migrations.AddConstraint(
            model_name='allowancerequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decided_at__isnull', True), ('status__in', ('PENDING_PM', 'PENDING_FINANCE'))), models.Q(('decided_at__isnull', False), ('status__in', ('APPROVED', 'PAID', 'REJECTED'))), _connector='OR'), name='a_decided_allowance_records_when'),
        ),
        migrations.AddConstraint(
            model_name='casual',
            constraint=models.UniqueConstraint(fields=('organization', 'id_number_key'), name='uniq_casual_id_number_per_org'),
        ),
        migrations.AddConstraint(
            model_name='casual',
            constraint=models.UniqueConstraint(condition=models.Q(('client_uuid__isnull', False)), fields=('organization', 'client_uuid'), name='uniq_casual_client_uuid_per_org'),
        ),
        migrations.AddConstraint(
            model_name='expensecasualline',
            constraint=models.CheckConstraint(condition=models.Q(('days__gt', 0)), name='a_casual_works_days'),
        ),
        migrations.AddConstraint(
            model_name='expensecasualline',
            constraint=models.UniqueConstraint(fields=('expense', 'casual'), name='uniq_casual_once_per_expense'),
        ),
    ]
