# Generated by Django 5.2.17 on 2026-10-09 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_asset_register'),
        ('commercials', '0006_requests_for_pending_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectexpense',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='assets.asset'),
        ),
    ]
