# Generated by Django 5.2.17 on 2026-10-09 16:06

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_enable_rls'),
        ('commercials', '0007_asset_register'),
        ('core', '0019_stage2_models'),
        ('locations', '0003_enable_rls'),
        ('network', '0009_subcontractor_rls'),
        ('receiving', '0008_earmarks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='allowancerequest',
            name='over_budget_by',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='allowancerequest',
            name='over_budget_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='over_budget_by',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='over_budget_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('share_type', models.CharField(choices=[('PERCENT', 'Percent of the contract value'), ('AMOUNT', 'Fixed amount')], max_length=10)),
                ('share_value', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('condition', models.CharField(choices=[('NONE', 'Due at once'), ('ALL_SITES_ACCEPTED', 'Due when every site is accepted'), ('DATE', 'Due on a date')], default='NONE', max_length=20)),
                ('condition_date', models.DateField(blank=True, null=True)),
                ('due_notified_on', models.DateField(blank=True, null=True)),
                ('overdue_notified_on', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='milestones', to='network.project')),
            ],
            options={
                'ordering': ('project_id', 'sequence'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MilestoneReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=500)),
                ('received_on', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='milestone_receipts', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='commercials.projectmilestone')),
            ],
            options={
                'ordering': ('received_on', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MilestoneInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=500)),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='milestone_invoices', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='commercials.projectmilestone')),
            ],
            options={
                'ordering': ('invoice_date', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SitePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=50)),
                ('purchase_date', models.DateField()),
                ('destination', models.CharField(choices=[('USED_AT_SITE', 'Used at the site'), ('INTO_YARD', 'Brought into the yard')], default='USED_AT_SITE', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='The sum of the lines, excluding VAT (D24). Set by the service.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('PENDING_PM', 'Waiting on the project manager'), ('PENDING_FINANCE', 'Waiting on Finance'), ('APPROVED', 'Approved — counts against the project'), ('PAID', 'Paid'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING_PM', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.CharField(blank=True, max_length=500)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('over_budget_by', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('over_budget_reason', models.CharField(blank=True, max_length=500)),
                ('photos_expected', models.PositiveSmallIntegerField(default=0)),
                ('client_uuid', models.UUIDField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('gate_in', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='site_purchase', to='receiving.gatein')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='site_purchases', to='network.project')),
                ('receive_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='locations.location')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='site_purchases_recorded', to=settings.AUTH_USER_MODEL)),
                ('reverses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='commercials.sitepurchase')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='site_purchases', to='network.site')),
            ],
            options={
                'ordering': ('-purchase_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SitePurchaseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('uom', models.CharField(blank=True, max_length=30)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogue.itemtype')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='commercials.sitepurchase')),
            ],
            options={
                'ordering': ('id',),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Subcontract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=50)),
                ('contract_value', models.DecimalField(decimal_places=2, help_text='Excluding VAT (D24).', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_terms', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed')], db_index=True, default='ACTIVE', max_length=10)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcontracts_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcontracts', to='network.project')),
                ('sites', models.ManyToManyField(blank=True, related_name='subcontracts', to='network.site')),
                ('subcontractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcontracts', to='network.subcontractor')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SubcontractPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('paid_on', models.DateField()),
                ('reference', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING_PM', 'Waiting on the project manager'), ('APPROVED', 'Approved — counts against the project'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING_PM', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.CharField(blank=True, max_length=500)),
                ('client_uuid', models.UUIDField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcontract_payments', to=settings.AUTH_USER_MODEL)),
                ('reverses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='commercials.subcontractpayment')),
                ('subcontract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='commercials.subcontract')),
            ],
            options={
                'ordering': ('-paid_on', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='projectmilestone',
            constraint=models.UniqueConstraint(fields=('project', 'sequence'), name='uniq_milestone_sequence_per_project'),
        ),
        migrations.AddConstraint(
            model_name='projectmilestone',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('condition', 'DATE'), ('condition_date__isnull', False)), models.Q(models.Q(('condition', 'DATE'), _negated=True), ('condition_date__isnull', True)), _connector='OR'), name='a_milestone_date_goes_with_a_date_condition'),
        ),
        migrations.AddConstraint(
            model_name='projectmilestone',
            constraint=models.CheckConstraint(condition=models.Q(('share_value__gt', 0)), name='a_milestone_has_a_share'),
        ),
        migrations.AddConstraint(
            model_name='projectmilestone',
            constraint=models.CheckConstraint(condition=models.Q(('share_type', 'AMOUNT'), ('share_value__lte', 100), _connector='OR'), name='a_milestone_percent_is_at_most_100'),
        ),
        migrations.AddConstraint(
            model_name='milestonereceipt',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='a_milestone_receipt_has_an_amount'),
        ),
        migrations.AddConstraint(
            model_name='milestonereceipt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('void_reason', ''), ('voided_at__isnull', True), ('voided_by__isnull', True)), models.Q(('voided_at__isnull', False), ('voided_by__isnull', False), models.Q(('void_reason', ''), _negated=True)), _connector='OR'), name='a_voided_milestone_receipt_records_who_when_why'),
        ),
        migrations.AddConstraint(
            model_name='milestoneinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='a_milestone_invoice_has_an_amount'),
        ),
        migrations.AddConstraint(
            model_name='milestoneinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('invoice_number', ''), _negated=True), name='a_milestone_invoice_has_a_number'),
        ),
        migrations.AddConstraint(
            model_name='milestoneinvoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('void_reason', ''), ('voided_at__isnull', True), ('voided_by__isnull', True)), models.Q(('voided_at__isnull', False), ('voided_by__isnull', False), models.Q(('void_reason', ''), _negated=True)), _connector='OR'), name='a_voided_milestone_invoice_records_who_when_why'),
        ),
        migrations.AddIndex(
            model_name='sitepurchase',
            index=models.Index(fields=['organization', 'project', 'status'], name='commercials_organiz_d98b67_idx'),
        ),
        migrations.AddIndex(
            model_name='sitepurchase',
            index=models.Index(fields=['organization', 'status'], name='commercials_organiz_d65481_idx'),
        ),
        migrations.AddConstraint(
            model_name='sitepurchase',
            constraint=models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('organization', 'number'), name='uniq_site_purchase_number_per_org'),
        ),
        migrations.AddConstraint(
            model_name='sitepurchase',
            constraint=models.UniqueConstraint(condition=models.Q(('client_uuid__isnull', False)), fields=('organization', 'client_uuid'), name='uniq_site_purchase_client_uuid_per_org'),
        ),
        migrations.AddConstraint(
            model_name='sitepurchase',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decided_at__isnull', True), ('status__in', ('PENDING_PM', 'PENDING_FINANCE'))), models.Q(('decided_at__isnull', False), ('status__in', ('APPROVED', 'PAID', 'REJECTED'))), _connector='OR'), name='a_decided_site_purchase_records_when'),
        ),
        migrations.AddConstraint(
            model_name='sitepurchase',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('destination', 'INTO_YARD'), ('receive_into__isnull', False)), models.Q(('destination', 'USED_AT_SITE'), ('receive_into__isnull', True)), _connector='OR'), name='a_yard_purchase_says_where_it_goes'),
        ),
        migrations.AddConstraint(
            model_name='sitepurchaseline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='a_purchase_line_has_a_quantity'),
        ),
        migrations.AddConstraint(
            model_name='sitepurchaseline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='a_purchase_line_price_is_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='sitepurchaseline',
            constraint=models.CheckConstraint(condition=models.Q(('item_type__isnull', False), models.Q(('description', ''), _negated=True), _connector='OR'), name='a_purchase_line_says_what_it_is'),
        ),
        migrations.AddIndex(
            model_name='subcontract',
            index=models.Index(fields=['organization', 'project', 'status'], name='commercials_organiz_25e061_idx'),
        ),
        migrations.AddConstraint(
            model_name='subcontract',
            constraint=models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('organization', 'number'), name='uniq_subcontract_number_per_org'),
        ),
        migrations.AddConstraint(
            model_name='subcontract',
            constraint=models.CheckConstraint(condition=models.Q(('contract_value__gt', 0)), name='a_subcontract_has_a_value'),
        ),
        migrations.AddIndex(
            model_name='subcontractpayment',
            index=models.Index(fields=['organization', 'subcontract', 'status'], name='commercials_organiz_c5ea11_idx'),
        ),
        migrations.AddConstraint(
            model_name='subcontractpayment',
            constraint=models.UniqueConstraint(condition=models.Q(('client_uuid__isnull', False)), fields=('organization', 'client_uuid'), name='uniq_subcontract_payment_client_uuid_per_org'),
        ),
        migrations.AddConstraint(
            model_name='subcontractpayment',
            constraint=models.CheckConstraint(condition=models.Q(('reference', ''), _negated=True), name='a_subcontract_payment_has_a_reference'),
        ),
        migrations.AddConstraint(
            model_name='subcontractpayment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decided_at__isnull', True), ('status', 'PENDING_PM')), models.Q(('decided_at__isnull', False), ('status__in', ('APPROVED', 'REJECTED'))), _connector='OR'), name='a_decided_subcontract_payment_records_when'),
        ),
    ]
