# Generated by Django 5.2.17 on 2026-10-09 17:19

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercials', '0009_stage2_rls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmilestone',
            name='share_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
