# Generated by Django 5.2.17 on 2026-10-09 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercials', '0010_milestone_share_nullable'),
        ('network', '0015_projectsite_organization_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepurchase',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='site_purchases', to='network.supplier'),
        ),
    ]
