# Generated by Django 5.2.17 on 2026-08-21 18:12

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], db_index=True, default='ACTIVE', max_length=20)),
                ('slug', models.SlugField(help_text="Subdomain addressing this tenant, e.g. 'silvertech'. Immutable.", max_length=63, unique=True, validators=[django.core.validators.RegexValidator(message='A subdomain may contain only lowercase letters, digits and hyphens, and may not begin or end with a hyphen.', regex='^[a-z0-9]([a-z0-9-]*[a-z0-9])?$')])),
                ('logo', models.FileField(blank=True, null=True, upload_to='organizations/logos/')),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('tax_pin', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to='core.organization')),
                ('money_tracking_enabled', models.BooleanField(default=False)),
                ('min_stock_enabled', models.BooleanField(default=False)),
                ('qr_labels_enabled', models.BooleanField(default=False)),
                ('asset_tag_enabled', models.BooleanField(default=False)),
                ('asset_tag_prefix_format', models.CharField(default='{org}-{category}-{seq:06d}', help_text='Format for generated internal asset tags, e.g. SLV-RRU-000123.', max_length=100)),
                ('client_waybill_enabled', models.BooleanField(default=False)),
                ('attachments_enabled', models.BooleanField(default=True)),
                ('attachments_required_gate_in', models.BooleanField(default=False)),
                ('attachments_required_gate_out', models.BooleanField(default=False)),
                ('signature_required_on_release', models.BooleanField(default=False)),
                ('gate_pass_expiry_hours', models.PositiveIntegerField(default=24)),
                ('allow_self_approval', models.BooleanField(default=False)),
                ('approval_escalation_hours', models.PositiveIntegerField(default=24)),
                ('allow_document_amendment', models.BooleanField(default=False)),
                ('retention_months', models.PositiveIntegerField(default=84)),
                ('timezone', models.CharField(default='Africa/Nairobi', max_length=64)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('notification_channels', models.JSONField(blank=True, default=dict)),
                ('notification_matrix', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name_plural': 'organization settings',
            },
        ),
    ]
