# Generated by Django 5.2.17 on 2026-08-21 18:36

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_identifier', models.CharField(blank=True, max_length=254)),
                ('action', models.CharField(choices=[('LOGIN_SUCCEEDED', 'Login succeeded'), ('LOGIN_FAILED', 'Login failed'), ('LOGOUT', 'Logout'), ('PASSWORD_RESET_REQUESTED', 'Password reset requested'), ('PASSWORD_CHANGED', 'Password changed'), ('USER_CREATED', 'User created'), ('USER_UPDATED', 'User updated'), ('USER_DEACTIVATED', 'User deactivated'), ('PERMISSION_CHANGED', 'Permission changed'), ('ROLE_CREATED', 'Role created'), ('ROLE_UPDATED', 'Role updated'), ('ROLE_DELETED', 'Role deleted'), ('SETTINGS_CHANGED', 'Settings changed'), ('ORGANIZATION_SUSPENDED', 'Organization suspended'), ('ORGANIZATION_REINSTATED', 'Organization reinstated'), ('DOCUMENT_POSTED', 'Document posted'), ('DOCUMENT_VOIDED', 'Document voided'), ('DOCUMENT_AMENDED', 'Document amended'), ('STATUS_CHANGED', 'Status changed'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, max_length=40)),
                ('target_type', models.CharField(blank=True, db_index=True, max_length=100)),
                ('target_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('target_label', models.CharField(blank=True, help_text='How the target read at the time, e.g. a document number.', max_length=255)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('auth_method', models.CharField(blank=True, choices=[('PASSWORD', 'Password'), ('WEBAUTHN', 'Fingerprint or platform authenticator'), ('SYSTEM', 'Automatic, no human actor')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('actor', models.ForeignKey(blank=True, help_text='Null for automatic actions and for failed logins with an unknown identifier.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
            ],
            options={
                'ordering': ('-occurred_at',),
                'indexes': [models.Index(fields=['organization', '-occurred_at'], name='core_auditl_organiz_8c5707_idx'), models.Index(fields=['organization', 'target_type', 'target_id'], name='core_auditl_organiz_7779cc_idx'), models.Index(fields=['organization', 'action', '-occurred_at'], name='core_auditl_organiz_541d6f_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
