# Generated by Django 5.2.17 on 2026-08-21 18:41

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auditlog_append_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('GATE_IN', 'Goods received note'), ('GATE_OUT', 'Gate pass'), ('STOCK_COUNT', 'Stock count'), ('TRANSFER', 'Stock transfer'), ('DISPOSITION', 'Quarantine disposition'), ('DISPOSAL', 'Disposal'), ('CLIENT_RETURN', 'Client return waybill'), ('CUSTODY_TRANSFER', 'Custody transfer')], max_length=30)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'document_type'), name='uniq_sequence_per_org_and_type')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
