# Generated by Django 5.2.17 on 2026-08-21 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_auditlog_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN_SUCCEEDED', 'Login succeeded'), ('LOGIN_FAILED', 'Login failed'), ('LOGOUT', 'Logout'), ('PASSWORD_RESET_REQUESTED', 'Password reset requested'), ('PASSWORD_CHANGED', 'Password changed'), ('USER_CREATED', 'User created'), ('USER_UPDATED', 'User updated'), ('USER_DEACTIVATED', 'User deactivated'), ('PERMISSION_CHANGED', 'Permission changed'), ('ROLE_CREATED', 'Role created'), ('ROLE_UPDATED', 'Role updated'), ('ROLE_DELETED', 'Role deleted'), ('SETTINGS_CHANGED', 'Settings changed'), ('ORGANIZATION_SUSPENDED', 'Organization suspended'), ('ORGANIZATION_REINSTATED', 'Organization reinstated'), ('DOCUMENT_POSTED', 'Document posted'), ('DOCUMENT_VOIDED', 'Document voided'), ('DOCUMENT_AMENDED', 'Document amended'), ('STATUS_CHANGED', 'Status changed'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CUSTODY_TRANSFERRED', 'Custody transferred'), ('VARIANCE_RAISED', 'Variance raised'), ('VARIANCE_RESOLVED', 'Variance resolved')], db_index=True, max_length=40),
        ),
    ]
