# Generated by Django 5.2.17 on 2026-09-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_attachment_audit_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='sms_credit_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='sms_credit_low_threshold',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
