# Generated by Django 5.2.17 on 2026-09-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_organizationsettings_sms_credit_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='project_release_notify_above',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tell the owner when project material above this value is approved, excluding VAT. Empty means never.', max_digits=14, null=True),
        ),
    ]
