# Generated by Django 5.2.17 on 2026-09-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_organizationsettings_project_release_notify_above'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsequence',
            name='highest_issued',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documentsequence',
            name='prefix',
            field=models.CharField(blank=True, help_text='Leave empty to use the default for this document type.', max_length=10),
        ),
        migrations.AddField(
            model_name='documentsequence',
            name='width',
            field=models.PositiveSmallIntegerField(default=6, help_text='How many digits the number is padded to.'),
        ),
        migrations.AlterField(
            model_name='documentsequence',
            name='document_type',
            field=models.CharField(choices=[('GATE_IN', 'Goods received note'), ('GATE_OUT', 'Gate pass'), ('STOCK_COUNT', 'Stock count'), ('TRANSFER', 'Stock transfer'), ('DISPOSITION', 'Quarantine disposition'), ('DISPOSAL', 'Disposal'), ('CLIENT_RETURN', 'Client return waybill'), ('CUSTODY_TRANSFER', 'Custody transfer'), ('PROJECT', 'Project'), ('JOB', 'Job')], max_length=30),
        ),
    ]
