# Generated by Django 5.2.17 on 2026-10-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_number_series_configurable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsequence',
            name='document_type',
            field=models.CharField(choices=[('GATE_IN', 'Goods received note'), ('GATE_OUT', 'Gate pass'), ('STOCK_COUNT', 'Stock count'), ('TRANSFER', 'Stock transfer'), ('DISPOSITION', 'Quarantine disposition'), ('DISPOSAL', 'Disposal'), ('CLIENT_RETURN', 'Client return waybill'), ('CUSTODY_TRANSFER', 'Custody transfer'), ('PROJECT', 'Project'), ('JOB', 'Job'), ('BOX', 'Box')], max_length=30),
        ),
    ]
