# Generated by Django 5.2.17 on 2026-10-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_boxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='release_scan_required',
            field=models.BooleanField(default=False),
        ),
    ]
