# Generated by Django 5.2.17 on 2026-10-09 07:40

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_backfill_seeded_role_permissions'),
        ('core', '0016_serial_corrected_audit_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='caption',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='attachment',
            name='client_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='allowance_limits',
            field=models.JSONField(blank=True, default=core.models.default_allowance_limits),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='finance_director_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.role'),
        ),
        migrations.AlterField(
            model_name='documentsequence',
            name='document_type',
            field=models.CharField(choices=[('GATE_IN', 'Goods received note'), ('GATE_OUT', 'Gate pass'), ('STOCK_COUNT', 'Stock count'), ('TRANSFER', 'Stock transfer'), ('DISPOSITION', 'Quarantine disposition'), ('DISPOSAL', 'Disposal'), ('CLIENT_RETURN', 'Client return waybill'), ('CUSTODY_TRANSFER', 'Custody transfer'), ('PROJECT', 'Project'), ('JOB', 'Job'), ('BOX', 'Box'), ('ALLOWANCE', 'Allowance request')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.UniqueConstraint(condition=models.Q(('client_uuid__isnull', False)), fields=('organization', 'client_uuid'), name='uniq_attachment_client_uuid_per_org'),
        ),
    ]
