# Generated by Django 5.2.17 on 2026-10-09 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_finance_role'),
        ('core', '0017_finance_settings_attachment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='clock_accuracy_cap_m',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='clock_auto_close_hour',
            field=models.PositiveSmallIntegerField(default=18, validators=[django.core.validators.MaxValueValidator(23)]),
        ),
        migrations.AddConstraint(
            model_name='organizationsettings',
            constraint=models.CheckConstraint(condition=models.Q(('clock_auto_close_hour__gte', 0), ('clock_auto_close_hour__lte', 23)), name='clock_auto_close_hour_0_to_23'),
        ),
        migrations.AddConstraint(
            model_name='organizationsettings',
            constraint=models.CheckConstraint(condition=models.Q(('clock_accuracy_cap_m__gte', 1)), name='clock_accuracy_cap_positive'),
        ),
    ]
