# Generated by Django 5.2.17 on 2026-10-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_organizationsettings_clock_accuracy_cap_m_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsequence',
            name='document_type',
            field=models.CharField(choices=[('GATE_IN', 'Goods received note'), ('GATE_OUT', 'Gate pass'), ('STOCK_COUNT', 'Stock count'), ('TRANSFER', 'Stock transfer'), ('DISPOSITION', 'Quarantine disposition'), ('DISPOSAL', 'Disposal'), ('CLIENT_RETURN', 'Client return waybill'), ('CUSTODY_TRANSFER', 'Custody transfer'), ('PROJECT', 'Project'), ('JOB', 'Job'), ('BOX', 'Box'), ('ALLOWANCE', 'Allowance request'), ('SITE_PURCHASE', 'Site purchase'), ('SUBCONTRACT', 'Subcontract')], max_length=30),
        ),
    ]
